# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv:
  - .env

vars:
  MAINFILE: ./cmd/server/main.go

tasks:
  default:
    desc: Runs the project
    cmds:
      - task: swag
      - go run {{.MAINFILE}}
    silent: false

  build:
    cmds:
      - go build -o ./bin/sub-service.exe {{.MAINFILE}}

  swag:
    cmds:
      - swag init -g {{.MAINFILE}} -o docs
    sources:
      - {.MAINFILE}
      - internal/handler/*.go
      - internal/model/*.go
    generates:
      - docs/docs.go
      - docs/swagger.json
      - docs/swagger.yaml

  up:
    desc: Apply next new migration (if exists)
    cmds:
      - goose up

  down:
    desc: Rall back the last migration
    cmds:
      - goose down

  create:*:
    desc: Create a new migration file with name from CLI arguments after ":"
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - goose create {{.NAME}} sql

  test:
    desc: "Запуск тестов"
    aliases: [t]
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" = "" ]; then
          go test -v -count=1 ./...
        else
          go test -v -count=1 {{.CLI_ARGS}}
        fi
    silent: false

  test-all:
    desc: "Запуск всех тестов с флагами"
    cmds:
      - go test -v -count=1 -cover -timeout=30s ./...
    silent: false