basePath: /api/v1
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
      errors:
        items:
          $ref: '#/definitions/model.ValidationError'
        type: array
    type: object
  handler.TotalCostResponse:
    properties:
      total_cost:
        type: integer
    type: object
  model.CreateSubscriptionInput:
    properties:
      end_date:
        type: string
      price:
        minimum: 0
        type: integer
      service_name:
        minLength: 2
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  model.Subscription:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  model.SubscriptionPageResponse:
    properties:
      content:
        items:
          $ref: '#/definitions/model.Subscription'
        type: array
      hasNext:
        type: boolean
      hasPrevious:
        type: boolean
      numberOfElements:
        type: integer
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
    type: object
  model.UpdateSubscriptionInput:
    properties:
      end_date:
        type: string
      price:
        minimum: 0
        type: integer
      service_name:
        minLength: 2
        type: string
      start_date:
        type: string
    type: object
  model.ValidationError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для агрегации данных об онлайн подписках пользователей
  title: Subscription Service API
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Возвращает список подписок с фильтрацией и пагинацией
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - default: 10
        description: Количество записей на странице (максимум 100)
        in: query
        name: size
        required: true
        type: integer
      - default: 1
        description: Страница (начиная с 1)
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SubscriptionPageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Список подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создает новую запись о подписке пользователя
      parameters:
      - description: Данные для создания подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.CreateSubscriptionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Создание новой подписки
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Удаляет подписку по её ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Удаление подписки
      tags:
      - subscriptions
    get:
      description: Возвращает информацию о подписке по её ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получение подписки по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет информацию о подписке по её ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      - description: Данные для обновления подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSubscriptionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Обновление подписки
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      description: |-
        Возвращает суммарную стоимость всех подписок за выбранный период с фильтрацией
        Если end_date не задан, то считается за период в 1 календарный месяц
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - default: 01-2026
        description: Дата начала периода
        in: query
        name: start_date
        required: true
        type: string
      - default: 02-2026
        description: Дата окончания периода (не включая). При отсутствии принимается
          период в 1 месяц
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TotalCostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Подсчет суммарной стоимости подписок
      tags:
      - subscriptions
  /uuid:
    get:
      description: Возвращает строку UUID
      produces:
      - text/plain
      responses:
        "200":
          description: some_uuid
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Генерация UUID v7 (для тестирования)
      tags:
      - util
schemes:
- http
- https
swagger: "2.0"
